---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install VLC
      apt:
        name: [vlc, vlc-plugin-vlsub]
        state: present
...
