---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install redshift-gtk
      apt:
        name: redshift-gtk
        state: present
        update_cache: yes
...
