---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Add firefox PPA
      apt_repository:
        repo: "ppa:ubuntu-mozilla-daily/ppa"
        state: present

    - name: Install firefox
      apt:
        package: [firefox-trunk]
        update_cache: yes
        state: present
...
