---
- name: Install headless libvirt instance
  apt:
    name:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - libguestfs-tools
      - genisoimage
      - virtinst
      - libosinfo-bin
    state: present

- name: Add maintenance user to kvm group
  user:
    name: maintenance
    groups: kvm
    append: yes


- name: Add ansible user to kvm group
  user:
    name: maintenance
    groups: kvm
    append: yes

- name: Set up a network bridge
  include_role:
    name: bridge
  when: setup_bridge is defined and setup_bridge

...
