---
- name: Add torbrowser-launcher PPA
  apt_repository:
    repo: "ppa:micahflee/ppa"
    state: present

- name: Install torbrowser-launcher
  apt:
    package: torbrowser-launcher
    update_cache: yes
    state: present
...
