---
# This script does some universal setup on the targeted machine(s).
# It installs python, creates ansible and manual maintenance users,
# and tightens SSH security settings.

- hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  vars_files:
    - vars/ssh_keys.yml

  roles:
    - role: raw-python
    - role: core
      ssh_port: 666
...
