---
# TODO: Uncomment
#- name: Common configuration
  #  import_playbook: core.yml
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  vars_files:
    - vars/devbox.yml

  roles:
    - {role: ansible}
    - {role: locales}

    - {role: docker, when: install_containerization == true}
    - {role: docker-compose, when: install_containerization == true}
    - {role: lxd, when: install_containerization == true}

    - {role: virtualbox, username: "{{ ansible_user_id }}", when: install_virtualization == true}

    - {role: firefox, when: install_desktop == true}
    - {role: thunderbird, when: install_desktop == true}
    - {role: libreoffice, when: install_desktop == true}
    - {role: wine, when: install_desktop == true}
    - {role: flatpak, when: install_desktop == true}
    - {role: redshift, when: install_desktop == true}
    - {role: syncthing, when: install_desktop == true}
    - {role: veracrypt, when: install_desktop == true}
    - {role: zim, when: install_desktop == true}
    - {role: i3, when: install_desktop == true}
    - {role: anki, when: install_desktop == true}
    - {role: evince, when: install_desktop == true}
    - {role: wine, when: install_desktop == true}
    - {role: torbrowser, when: install_desktop == true and install_privacy == true}
    - {role: megasync, when: install_desktop == true and install_cloud == true}
    - {role: printing, when: install_printing == true}
    - {role: discord, when: install_entertainment == true}
    - {role: kodi, when: install_entertainment == true}
    - {role: openra, when: install_entertainment == true}
    - {role: nethack, when: install_entertainment == true}
    - {role: bsdgames, when: install_entertainment == true}
    - {role: steam, when: install_entertainment == true}
    - {role: cmus, when: install_entertainment == true}
    - {role: playonlinux, when: install_entertainment == true}
    - {role: vlc, when: install_entertainment == true}

    - {role: golang, when: install_devtools == true}
    - {role: python, when: install_devtools == true}
    - {role: nodejs, when: install_devtools == true}
    - {role: texlive, when: install_devtools == true}
    - {role: vagrant, when: install_devtools == true}
    - {role: vim, when: install_devtools == true}
    - {role: vscode, when: install_devtools == true and install_desktop == true}
    - {role: shellcheck, when: install_devtools == true}
    - {role: zeal, when: install_devtools == true and install_desktop == true}
    - {role: vbindiff, when: install_devtools == true}
    - {role: tmux, when: install_devtools == true}

    - {role: tlp, when: install_laptop == true}
