---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  vars_files:
    - vars/ssh_keys.yml

  tasks:
  - name: Install kvm
    include_role:
      name: kvm
    vars:
      add_kvm_user: true
      setup_bridge: true
      kvm_ssh_keys: '{{ ssh_keys }}'
...
