---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Make sure python is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
...
