---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Create ubuntu bionic test container
    lxd_container:
      name: ubuntu-bionic-ansible
      state: started
      wait_for_ipv4_addresses: true
      source:
        type: image
        mode: pull
        server: https://images.linuxcontainers.org
        protocol: lxd
        alias: ubuntu/bionic/amd64
        profiles: ["default"]
      ephemeral: true
      config:
        security.privileged: "true"
        security.nesting: "true"

      # LXD snap doesn't expose unix socket at the default location
      url: unix:///var/snap/lxd/common/lxd/unix.socket
      timeout: 300

  - name: Install python in the container
    raw: bash -c "test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)"
    args:
      executable: /bin/sh
    register: output
    changed_when: output.stdout
    delegate_to: ubuntu-bionic-ansible
...
