---
config: {}
networks: []
storage_pools:
- config: {} # yamllint disable-line
  description: ""
  name: default
  driver: dir
profiles:
- config: {} # yamllint disable-line
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: br0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
cluster: null
...
