---
# TODO:
# Introduce variable to configure whether to install games
# TODO:
# Use a PPA/other source w/ automatic updates once provided by upstream
- name: Get URL pointing to the latest OpenRA .deb
  # Ignore linter warning abot wget - it's cleaner than the alternative.
  args:
    warn: false
  shell: wget --quiet https://github.com/OpenRA/OpenRA/releases -O- | grep "_all.deb" | grep release | cut -d '"' -f2 | head -1 | sed "s/^/https:\/\/github.com/"
  register: openra_latest_deb_url
  failed_when: openra_latest_deb_url.rc > 0
  changed_when: False

- name: Install OpenRA
  apt:
    deb: "{{ openra_latest_deb_url.stdout }}"
    state: present
...
