---
- name: Ensure dependencies of dotfile installation script are present
  become: yes
  become_user: root
  package:
    name: [git, stow, python3-minimal]
    state: present

- name: Clone dotfiles git repo into the home directory
  become: yes
  become_user: '{{ username }}'
  become_method: sudo
  git:
    repo: 'https://github.com/casept/dotfiles'
    dest: ~/dotfiles/
    update: yes
    recursive: true

- name: Install dotfiles
  become: yes
  become_user: '{{ username }}'
  become_method: sudo
  shell: cd ~/dotfiles && python3 install.py
  register: dotfiles_output
  changed_when: "'No files changed' not in dotfiles_output.stdout"
...
