---
- import_playbook: neovim.yml
- hosts: all
  become: yes
  become_user: '{{local_user}}'
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install extensions
      command: code --install-extension '{{item}}'
      register: code
      with_items:
        - AdamCaviness.theme-monokai-dark-soda
        - Compulim.compulim-vscode-closetag
        - DavidAnson.vscode-markdownlint
        - Shan.code-settings-sync
        - Tyriar.vscode-terminal-here
        - actboy168.lua-debug
        - bungcip.better-toml
        - cssho.vscode-svgviewer
        - eamodio.gitlens
        - hdg.live-html-previewer
        - jbw91.theme-material-dark-soda
        - lukehoban.Go
        - marcostazi.VS-code-vagrantfile
        - ms-python.python
        - ms-vscode.cpptools
        - robertohuertasm.vscode-icons
        - shardulm94.trailing-spaces
        - timonwong.shellcheck
        - vittorioromeo.expand-selection-to-scope
        - vscodevim.vim
        - wayou.vscode-todo-highlight
      changed_when: "'is already installed.' not in code.stdout"
...
