---
- name: Ensure apt can download over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add vscode repo key
  apt_key:
    # Key is the same for ubuntu and debian
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add vscode repo
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    # Needed so vscode doesn't generate a duplicate file in sources.list.d/
    filename: vscode
    state: present

- name: Install vscode
  apt:
    name: code
    state: present
    update_cache: yes


- import_playbook: extensions.yml
...
