---
- name: Add neovim repo (needed for ex commands from the vim plugin to work)
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    state: present

- name: Install neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
...
