---
- name: Ensure snapd is installed
  package:
    name: snapd
    state: present


- name: Ensure system-packaged LXD is removed
  apt:
    name: [lxd, lxd-client]
    state: absent
    autoremove: true

- name: Check whether LXD snap is already installed
  # TODO: Replace with snap module once available
  command: "snap list"
  register: installed_snaps
  changed_when: false

- name: Install LXD snap
  command: "snap install lxd"
  when: "'lxd' not in installed_snaps.stdout"


- name: Initialize LXD
  args:
    warn: false
  shell: lxd init --auto && touch /var/lib/lxd/ansible-lxd-init creates=/var/lib/lxd/ansible-lxd-init
