---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Ensure apt can download over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add node signing key
      apt_key:
        # Key is the same for ubuntu and debian
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add node repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_8.x {{ansible_distribution_release}} main
        state: present

    - name: Install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
...
