---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Install playonlinux
      apt:
        package: playonlinux
        state: present
...
