---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Install thunderbird
      apt:
        package: thunderbird
        state: present
...
