---
- name: Install CUPS
  apt:
    package: cups
    state: present
- name: Install system-config-printer
  apt:
    package: system-config-printer-gnome
    state: present

- import_tasks: drivers.yml
