---
- name: Add the user's group
  become: yes
  become_user: root
  become_method: sudo
  group:
    name: '{{ username }}'
    state: present

- name: Add user with password
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: '{{ username }}'
    group: '{{ username }}'
    password: '{{ password }}'
    createhome: yes
    home: '/home/{{ username }}'
    shell: /bin/bash
    state: present
  when: password is defined

- name: Add user with disabled password
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: '{{ username }}'
    group: '{{ username }}'
    createhome: yes
    home: '/home/{{ username }}'
    shell: /bin/bash
    state: present
  when: password is not defined

- name: Ensure sudo is installed
  become: yes
  become_user: root
  become_method: sudo
  package:
    name: sudo
    state: present

- name: Make the user a sudoer
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: '{{ username }}'
    groups: sudo
    append: yes

- name: Ensure the nopasswders group exists
  become: yes
  become_user: root
  become_method: sudo
  group:
    name: nopasswders
    state: present
    system: yes
  when: passwordless_sudo


- name: Check whether the nopasswders file exists in /etc/sudoers.d/
  become: yes
  become_user: root
  become_method: sudo
  stat:
    path: /etc/sudoers.d/nopasswders
  register: nopasswders_exists

- name: Create the nopasswders config file in /etc/sudoers.d/
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: /etc/sudoers.d/nopasswders
    state: touch
    mode: 0440
    owner: root
    group: root
  when: nopasswders_exists.stat.exists == False


- name: Allow the nopasswders group passwordless sudo
  become: yes
  become_user: root
  become_method: sudo
  lineinfile:
    dest: /etc/sudoers.d/nopasswders
    state: present
    regexp: '^%nopasswders'
    line: '%nopasswders ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  when: passwordless_sudo

- name: Add the user to nopasswders to allow passwordless sudo
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: '{{ username }}'
    groups: nopasswders
    append: yes
    state: present
  when: passwordless_sudo

- name: Ensure user's .ssh directory exists
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: '/home/{{ username }}/.ssh'
    state: directory
    mode: 700
    owner: '{{ username }}'

- name: Ensure becoming unprivileged user is always possible
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: acl
    state: present

- name: Add authorized SSH keys
  become: yes
  become_user: '{{ username }}'
  become_method: sudo
  authorized_key:
    key: '{{ item }}'
    user: '{{ username }}'
    state: present
  loop: '{{ user_ssh_keys }}'
...
