---
# Taken from https://forums.virtualbox.org/viewtopic.php?f=6&t=82761
- name: Get virtualbox version
  shell: "vboxmanage --help | head -n 1 | awk '{print $NF}'"
  register: vbox_version

- name: Download VirtualBox extension pack
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{vbox_version.stdout}}/Oracle_VM_VirtualBox_Extension_Pack-{{vbox_version.stdout}}.vbox-extpack"
    dest: /tmp

- name: Install VirtualBox extension pack
  shell: "yes | VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack-{{vbox_version.stdout}}.vbox-extpack"
