---
- name: Enable apt downloads over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: true

- name: Add syncthing repo key
  apt_key:
    # Key is the same for ubuntu and debian
    url: https://syncthing.net/release-key.txt
    state: present

- name: Add syncthing repo
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present

- name: Install syncthing relay package
  apt:
    name: syncthing-relaysrv
    state: present
    update_cache: true

- name: Add syncthing relay user
  user:
    name: strelaysrv
    createhome: true
    home: /var/strelaysrv
    shell: /usr/sbin/nologin
    state: present

- name: Create provided by entry
  set_fact: provided_by_cmdline="-provided-by={{ provided_by }}"
  when: provided_by is defined


- name: Create rate limit entry
  set_fact: rate_limit_cmdline="-global-rate={{ rate_limit }}"
  when: rate_limit is defined

- name: Create systemd service
  template:
    src: templates/syncthing-relay.service.j2
    dest: /etc/systemd/system/syncthing-relay.service
  notify: Restart syncthing relay
...
