---
- name: Install i3 and some utilities
  with_items:
    - i3
    - i3lock
    - i3status
    - dmenu
    - feh
    - xautolock
    - dunst
  apt:
    name: "{{ item }}"
    state: present

- import_tasks: blueman.yml
- import_tasks: lightdm.yml
- import_tasks: networkmanager.yml
- import_tasks: playerctl.yml
- import_tasks: pulseaudio.yml
- import_tasks: scrot.yml
- import_tasks: caffeine.yml
- import_tasks: getoffthepc.yml
...
