---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install networkmanager stuff
      apt:
        name: network-manager-gnome
        state: present
...