---
- hosts: all
  become: yes
  become_user: '{{ local_username }}'
  become_method: sudo
  tasks:
    - name: Ensure user exists
      user:
        name: '{{ local_username }}'
        password: '{{ local_password }}'
        createhome: yes
        shell: /bin/bash
        state: present

    - name: Ensure sudo is installed
      package:
        name: sudo
        state: present

    - name: Make the user a sudoer
      user:
        name: '{{ local_username }}'
        groups: sudo
        append: yes

    - name: Permit the user to access arbitrary USB devices (needed for virtualbox USB passthrough)
      user:
        name: '{{ local_username }}'
        groups: vboxusers
        append: yes

    - name: Add authorized SSH key
      authorized_key:
        key: '{{ ssh_pubkey }}'
        user: '{{ local_username }}'
        state: present

    - name: Add SSH private key
      copy:
      content: '{{ ssh_key }}'
      dest: /home/'{{ local_username }}'/.ssh/'{{ key_file }}'
      mode: 0600
      owner: '{{ local_username }}'
...
