---
- name: Make sure python is installed
  become: true
  become_user: root
  gather_facts: false
  raw: bash -c "test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)"
  args:
    executable: /bin/sh
  register: output
  changed_when: output.stdout
...
