---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install discord
      apt:
        deb: "https://discordapp.com/api/download?platform=linux&format=deb"
        state: present
...
