---
- name: Enable apt downloads over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add docker repo key
  apt_key:
    # Key is the same for ubuntu and debian
    url: https://download.docker.com/linux/debian/gpg
    state: present
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable
    state: present

- name: Install docker package
  apt:
    name: docker-ce
    state: present
    update_cache: yes
...
