---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo 
  tasks:

    - name: Add a group which can sudo without a password
      group:
        name: nopasswders
        state: present
    - name: Actually let this group sudo
      lineinfile:
        #Some old distros don't support /etc/sudoers.d/
        dest: /etc/sudoers
        state: present
        regexp: '^%nopasswders'
        line: '%nopasswders ALL=(ALL) NOPASSWD: ALL'

    - name: Add an ansible user 
      #We use a separate group from "sudoers" because
      #we need to enable the group to use sudo without a password.
      #Setting this attribute for all users in the "sudo" group would be a security risk.
      user: name=ansible group=nopasswders state=present createhome=yes 

    - name: Copy SSH key and allow SSH access by ansible user 
      authorized_key:
        user: ansible
        #Replace this with your own pubkey
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwzwv1wj6QHXVzDbc2Ma6zMB7Y4Pm71Ye91OfmXIGSTUZgrNPZWWwWlJIEgJHdBjWrb5bgUxJ/FW4oVvtvGL09K+CN8srKBIRTkUmnjCeHOE6tl8/Nbhp5cqYOagmq3Dyz0w0JFnXhybht3X6HdKZrSQR0JMTjsHvAvdrPhvtFhqoqsX9hGVwL/gh7CpWop8/598impQDybIZByThsGsEVGUvvmwlb2FX5E5Q1z7bPoKALRfWX0oq79WHJtvoy4awN0chFTgMjc+eedT0M8PBcAv0KfNwiWMUiJzFecfxpsCTtWgd2RTjNdOCDOcjvr8m8KNBrTnSFGywnZlenAN2zZd+G4Cmc586C2A9fDnCI5i5mxRucE3w20m/RIKQf4FA/0jiFnh4M0e6XeZjJn2AfpYz3+W+2vlz/xld6hIbEmdzCSBQLz3q1CmecBJKfQKXujH1BnSOQcoFBWhs1y1dCFv9kFndKKJpNh6HInRCgy3+/J4QnonZNtc8qyRqvlTz9DdLyuL2WYQwcErmOdlgOpK/x9kjyP3367sNJBECdrVOiU3mpxNJdnhGCxmnm/FRTOXPgQX5yrmborwgGBgDmFNU5DHjBaysKXRcXc+uwD2CxXu3p6ZSDH//PA2q3KL05cLR3wv5u/ytILEeR2XPUPIiMoPAE/5yI9MgDtHXGJQ== david@t400" 
        state: present
...
