---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
    - name: Download and install golang
      unarchive:
        src: https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: true

    - name: Symlink binaries in $GOROOT/bin into /usr/local/bin
      file:
        src: /usr/local/go/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        state: link
      with_items:
        - go
        - godoc
        - gofmt 
...
