---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
    - name: Install TLP 
      apt:
        name: [tlp, tlp-rdw, smartmontools, ethtool] 
        state: present
        update_cache: yes 

    - name: Install thinkpad-specific tools
      apt:
        name: [tp-smapi-dkms, acpi-call-dkms]
        state: present

    - name: Start TLP for the first time
      shell: tlp start      
...
