---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no 

  tasks:
    - name: Add veracrypt PPA
      apt_repository:
        repo: "ppa:unit193/encryption"
        state: present

    - name: Install veracrypt
      apt:
        package: [veracrypt]
        update_cache: yes
        state: latest
