---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Enable apt downloads over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add syncthing repo key
      apt_key:
        # Key is the same for ubuntu and debian
        url: https://syncthing.net/release-key.txt
        state: present

    - name: Add syncthing repo
      apt_repository:
        repo: deb https://apt.syncthing.net/ syncthing stable
        state: present

    - name: Install syncthing package
      apt:
        name: syncthing
        state: present
        update_cache: yes
...
