---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install pip
      apt:
        name:
          - python3-pip
        state: present
        update_cache: yes
    - name: Install ipython
      pip:
        executable: pip3
        name:
          - ipython
        state: present
...
